version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    restart: always
    volumes:
      - mongo_data:/data/db
      - mongo_fs:/data/fsdb

volumes:
  mongo_data:
  mongo_fs:
